moduleConfig:
  logger:
    dependencies:
    globalLogLevel: ERROR
    enableFileLogging: true
    logDirectory: .enigma/logs
    latestLogFileName: latest.log
    enableLogRotation: true
    maxLogFiles: 10
    enableConsoleLogging: false
    enableConsoleColors: true
    enableDevConsoleLogging: false
    includeTimestamp: true
    includeThreadId: false
    includeFrameNumber: true
    includeCategory: true
    flushImmediately: false
    categoryLogLevels:
      Engine: ERROR
      Renderer: ERROR
      Audio: ERROR
      Game: ERROR
  console:
    dependencies:
      - renderer
    defaultFontName: CaiziiFixedFont
    fontPath: .enigma/data/Fonts/
    defaultFontAspect: 0.7
    maxLinesDisplay: 40.5
    maxCommandHistory: 128
    startOpen: false
  audio:
    dependencies:
      - resource
    enableResourceIntegration: true
  resource:
    dependencies:
    baseAssetPath: .enigma/assets
    